Update postinstall script
* debian/opennebula-node.postinst.in: Update to dh_make “postinst.ex”
  standard.
  Factorize group membership test.
  Update “qemu.conf” instead of overriding it.

diff --git a/debian/opennebula-node.postinst.in b/debian/opennebula-node.postinst.in
--- a/debian/opennebula-node.postinst.in
+++ b/debian/opennebula-node.postinst.in
@@ -1,29 +1,67 @@
 #!/bin/sh
+# postinst script for opennebula-node
+#
+# see: dh_installdeb(1)
 
 set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 ONEHOME=/var/lib/one
 ONE_GROUP=oneadmin
 ONE_USER=oneadmin
+QEMU_CONF=/etc/libvirt/qemu.conf
 
-if [ "$1" = "configure" ]; then
-    # Add oneadmin user into @LIBVIRTGRP@ group
-    if getent group @LIBVIRTGRP@ >/dev/null && ! getent group @LIBVIRTGRP@ | cut -f4 -d: | grep -q '\<$ONE_USER\>'; then
-        adduser $ONE_USER @LIBVIRTGRP@
-    fi
+is_in_group() {
+    getent group ${2} > /dev/null \
+      && id --name --groups ${1} | grep -q "\b${2}\b" > /dev/null
+}
 
-    # Add oneadmin user into kvm group
-    if getent group kvm >/dev/null && ! getent group kvm | cut -f4 -d: | grep -q '\<$ONE_USER\>'; then
-        adduser $ONE_USER kvm
-    fi
+set_qemu_option() {
+    sed -i -e "s,^#*$1[[:space:]]*=.*,$1 = $2," "${QEMU_CONF}"
+}
 
-    if [ -e /etc/libvirt/qemu.conf ]; then
-        cp /etc/libvirt/qemu.conf /etc/libvirt/qemu.conf.orig
+case "$1" in
+    configure)
+        # Add oneadmin user into @LIBVIRTGRP@ group
+        if ! is_in_group $ONE_USER @LIBVIRTGRP@; then
+            adduser $ONE_USER @LIBVIRTGRP@
+        fi
 
-        echo 'user  = "oneadmin"'    >  /etc/libvirt/qemu.conf
-        echo 'group = "oneadmin"'    >> /etc/libvirt/qemu.conf
-        echo 'dynamic_ownership = 0' >> /etc/libvirt/qemu.conf
-    fi
-fi
+        # Add oneadmin user into kvm group
+        if ! is_in_group $ONE_USER kvm; then
+            adduser $ONE_USER kvm
+        fi
+
+        if [ -e "${QEMU_CONF}" ]; then
+	    set_qemu_option user '"oneadmin"'
+	    set_qemu_option group '"oneadmin"'
+            set_qemu_option dynamic_ownership 0
+        fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
+
+exit 0
